### ISSUE TITLE
AccessDenied when publising images on S3

### ISSUE THREAD

**Issue by tonai** [reg-viz/reg-suit#148]
Hi,
I got the following error when running the `npx reg-suit run` command:
```
AccessDenied: Access Denied
    at Request.extractError (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/tocab/Projects/Test/formation-react/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:205:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20) {
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2019-07-10T09:16:26.196Z,
  requestId: 'ECBE4148B06567A6',
  extendedRequestId: 'MtF0i9hBX7aoPS0SOkAdqnSDiyJFCAxE0TeHn499ahF523r8vgoYK5ISW2+iixiHbtItty/ejMk=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 83.03007054278937
}
```

But my AWS credentials seems to work fine.
I have created a test file at the root of my project with the following code:
```js
const AWS = require('aws-sdk');
const fs = require('fs');

const s3 = new AWS.S3({apiVersion: '2006-03-01'});

const readStream = fs.createReadStream('./screenshot/index.png');
const params = {
  Bucket: 'reg-suit-59', 
  Key: 'image',
  Body: readStream
}
s3.upload(params, function (err, data) {
  if (err) console.log(err, err.stack);
  else     console.log(data);
});
```
And it has published the image on my S3 bucket.

Here is my regconfig.json file:
```json
{
  "core": {
    "workingDir": ".reg",
    "actualDir": "screenshot",
    "thresholdRate": 0,
    "addIgnore": true,
    "ximgdiff": {
      "invocationType": "client"
    }
  },
  "plugins": {
    "reg-keygen-git-hash-plugin": true,
    "reg-notify-gitlab-plugin": {
      "privateToken": "xxxxxxxxxxxxxxxx"
    },
    "reg-publish-s3-plugin": {
      "bucketName": "reg-suit-59"
    }
  }
}
```

Thanks in advance for any help.
Regards,

**Comment by Quramy** [comment]
Hi.

Sorry, I’m not familiar with AWS / IAM :bow:

reg-suit S3 plugin uses few S3 APIs:

- put object
- get object
- list object

https://github.com/reg-viz/reg-suit/blob/master/packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts

Please confirm your AWS IAM user has these permissions :pray:

**Comment by tonai** [comment]
Thank you for pointing me the code part.
In fact the problem is not about IAM permissions (here my IAM user has full access to S3).

It is more about the default `public-read` ACL.
When creating a S3 bucket on AWS, the default configuration block the public access.
Deactivating the blocking solved the problem.

Thanks for your support.
