### ISSUE TITLE
Unable to publish to s3 using latest `reg-publish-s3-plugin`

### ISSUE THREAD

**Issue by samturrell** [reg-viz/reg-suit#633]
## Describe the bug

Since upgrading to the latest `reg-publish-s3-plugin` version (0.13) i'm unable to publish the assets to s3. The command exits with the `Error: Region is missing` error message.

How can i define this variable? I've tried env variables as part of the github action step, but doesn't seem to be picking this up.

## Reproduced step

1. Run reg suit with the `reg-publish-s3-plugin` plugin

## Expected behavior

Assets upload to s3 successfully

## Actual behavior

The command is erroring with `Error: Region is missing` 

## Screenshots

```
$ /*****/actions-runner/_work/*****/node_modules/.bin/reg-suit run
[reg-suit] info version: 0.13.0
[reg-suit] info Detected the previous snapshot key: '8a4ebd0b6747639f601745d8247df3a7ccbdae71'
Error: Region is missing
    at default (/home/*****/actions-runner/_work/*****/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /home/*****/actions-runner/_work/*****/node_modules/@smithy/node-config-provider/dist-cjs/index.js:72:104
    at /home/*****/actions-runner/_work/*****/node_modules/@smithy/property-provider/dist-cjs/index.js:79:33
    at async coalesceProvider (/home/*****/actions-runner/_work/*****/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
    at async /home/*****/actions-runner/_work/*****/node_modules/@smithy/property-provider/dist-cjs/index.js:117:20
    at async region (/home/*****/actions-runner/_work/*****/node_modules/@smithy/config-resolver/dist-cjs/index.js:142:30)
    at async /home/*****/actions-runner/_work/*****/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:89:28
    at async /home/*****/actions-runner/_work/*****/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
    at async /home/*****/actions-runner/_work/*****/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by teradiot** [comment]
I also encountered the same error after updating to the latest version.
The issue was resolved by configuring the `region` in the sdkOptions of `regconfig.json`.

```json
{
  ...,
  "plugins": {
    "reg-publish-s3-plugin": {
      "sdkOptions": {
        "bucketName": "xxxx",
        "region": "us-east-1"
      }
    }
  }
}
```
